language: julia

os:
  - osx
  # - osx

julia:
  - 0.7
  # - 1.0
  # - nightly

notifications:
  email: false

# after_success:
#   - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
#   - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 0.7
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("DataStructures"); Pkg.add("Clp"); Pkg.add("Ipopt"); Pkg.add("MathProgBase"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip